config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'index#show'
  
  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  
  get '/signin' => 'sessions#new'
  get '/show' => 'sessions#show'
  post '/signin' => 'sessions#create'
  get '/signout' => 'sessions#destroy'

  get '/admin' => 'users#admin'
  get '/index' => 'index#show'

  resources :users do
    resources :images
  end



end


# if it doesn't work under user, then try sessions...

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  has_many :images, dependent: :destroy
  attr_accessor :password
  validates_confirmation_of :password
  validates :email, :presence => true, :uniqueness => true
  before_save :encrypt_password

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password,password_salt)
  end

  def self.authenticate(email, password)
    user = User.find_by "email = ?", email
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end
  end

  def authorize
    if !current_user
      flash[:alert] = "You need to sign in to view this page."
      redirect_to '/signin'
    end
  end

  def authorize_admin
    if !(current_user && current_user.admin)
      flash[:alert] = "You need admin privileges to view this page. Please sign in with an admin account"
      redirect_to '/signin'
    end
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :authorize, only: [:new, :edit, :show]

  def new
    @user = User.find(params[:user_id])
    @image = @user.images.new
    render :new
  end

  def edit 
    @user = User.find(params[:user_id])
    @image = Image.find(params[:id])
    render :edit
  end

  def update
    @image = Image.find(params[:id])
    @user = User.find(params[:user_id])
    if @image.update(image_params)
      redirect_to user_image_path(@user, @image)
    else
      render :edit
    end
  end

  def create
    @user = User.find(params[:user_id])
    @image = @user.images.new(image_params)
    @image.photo.attach(params[:image][:photo])
    if @image.save
      flash[:notice] = "Image uploaded"
      redirect_to  user_image_path(@user, @image)
    else
      flash[:error] = "There was a problem uploading your image."
      render :new
    end
  end

  def show
    @user = User.find(params[:user_id])
    @image = Image.find(params[:id])
    @images = @user.images
    render :show
  end

  def destroy
    @user = User.find(params[:user_id])
    @image = Image.find(params[:id])
    @image.destroy
    render :show
  end

  private
  def image_params
    params.require(:image).permit(:photo, :description)
  end 

end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def show
    render :show
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :authorize, only: [:show]
  def create
    @user = User.authenticate(params[:email], params[:password])
    if @user
      flash[:notice] = "You've signed in."
      session[:user_id] = @user.id
      # http://localhost:3000/users/8/images/new
      redirect_to show_path
    else
      flash[:alert] = "There was a problem signing in. Please try again."
      redirect_to signin_path
    end
  end

  def show
    @user = User.find(session[:user_id])
    # @user = User.authenticate(params[:email], params[:password])
    # session[:user_id] = @user.id
    render :show
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've signed out."
    redirect_to "/"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, only: [:show]
  before_action :authorize_admin, only: [:admin, :edit, :destroy] #method, not path

def new
  @user = User.new
end

def create
  @user = User.new(user_params)
  if @user.save
    flash[:notice] = "You've successfully signed up!"
    session[:user_id] = @user.id
    render :show
  else
    flash[:alert] = "There was a problem signing up."
    redirect_to '/signup'
  end
end

def show
  render :show
end

def admin
    @users = User.all
    render :admin_user
end

def edit
  @user = User.find(params[:id])
  render :edit
end

def destroy
  @users = User.all
  if User.find(session[:user_id]) == User.find(params[:id])
    flash[:notice] = "NO"
    render :admin_user
  else
    @user = User.find(params[:id])
    @user.destroy
    render :admin_user
  end
end

  private
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :admin)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/images/edit.html.erb
<div class="row">
  <div class="col-sm-4">
  <h4><%= @image.description%></h4><br>
  <% if @image.photo.attached? %>
    <%= image_tag(@image.photo, width: 200) %>
  <% end %>
  <br><br>
  <p><%= link_to "Delete image", user_image_path,
                  :data => {:confirm => "Are you sure?",
                  :method => "delete"} %></p>

  <p><%= link_to "Return to images", user_image_path %></p>
  </div>
  <div class="col-sm-5">
  <h1>Update Image </h1>
  <%= form_for [@user, @image] do |f| %>
    <br>
    <%= f.file_field :photo %>
    <br><br>
    <%= f.label :Name_or_Description %>:
    <%= f.text_field :description %>
    <br><br>
    <p><%= f.submit %></p>
  <% end %>
  </div>
</div>

app/views/images/new.html.erb
<h1>Add a new image:</h1>

<%= form_for [@user, @image] do |f| %>
  <br>
  <%= f.file_field :photo %>
  <br><br>
  <%= f.label :Name_or_Description %>:
  <%= f.text_field :description %>
  <br><br>
  <p><%= f.submit %></p>
<% end %>

app/views/images/show.html.erb
<h2>Your Image Gallery</h2>

<% if @user.images.any? %>
  <br>
  <div class="grid-container">
    <% @user.images.each do |image| %>
    
      <div class="grid-item">
        <% if image.photo.attached? %>
          <p style="text-align:center;"><%= image_tag(image.photo, width: 300) %></p>
        <% end %>
        <p style="text-align:center;"><%= link_to image.description, edit_user_image_path(@user, image) %></p>
        
        </div>
    <% end %>
  </div>
<% else %>
<ul>
  <li>
    <p>You currently have no images.</p>
  </li>
</ul>
<% end %>

<h5><%= link_to "add image", new_user_image_path(@user)%></h5> 

app/views/index/show.html.erb
<h1>Welcome to Stickr!</h1>
<hr>
<div class="row">
  <div class="col-sm-6">
    <p>Stickr is a website where you can create an account and upload pictures to the database for storage. To get started, simply click on "Sign up" to create a new account or "Sign in" to log in with an existing account. Once you are signed in, you can navigate to the <em><strong>Photos</strong></em> tab on the navigation bar and add new images or view existing images.</p>
    </div>
    <div class="col-sm-1">
  </div>
  <div class="col-sm-4">
    <img src="https://99designs.zendesk.com/hc/article_attachments/202090665/40749120150407-3-112nbtl" height="110">
  </div>
</div>
<br><br><br>
<div class="row">
  <div class="col-sm-5">
    <p>As a <b>Normal User</b>, you are allowed access to:</p>
    <ul>
      <li>Upload image files and add a name or description for the image. </li>
      <li>Edit any existing image in your gallery.</li>
      <li>Delete any existing image in your gallery.</li>
    </ul>
    </div>
    <div class="col-sm-1">
  </div>
  <div class="col-sm-5">
  <p>As an <b>Admin</b>, you are allowed access to:</p>
  <ul>
    <li>All features of a normal user.</li>
    <li>Access to the <b>Admin Dashboard</b></li>
    <li>View the list of all users in the database.</li>
    <li>Delete any users in the database.</li>
    <li>View, edit, delete any images in the database.</li>
  </ul>
</div>
<div class="col-sm-5">
</div>
<br><br><br>
<div class="row">
  <div class="col-sm-5">
    <p>Since this website is for educational purposes, I have created an admin account in the database with the following login:</p>
    <ul>
      <li>login: a@a.com</li>
      <li>password: a</li>
    </ul>
  </div>
  <div class="col-sm-1">
  </div>
  <div class="col-sm-5">
  <p style="text-align:center;"><img src="https://cdn1.iconfinder.com/data/icons/users-39/24/305-512.png" height="150"></p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StickR</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand abs" >StickR</a>
        <button class="navbar-toggler ms-auto" type="button" data-bs-toggle="collapse" data-bs-target="#collapseNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse" id="collapseNavbar">
            <ul class="navbar-nav">
                <li class="nav-item active">
                  <a class="nav-link active" aria-current="page" href="/">Home</a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="/show">Photos</a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="/admin">Admin Dashboard</a>
                </li>
            </ul>
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                <% if current_user %>
                <%# <a class="nav-link" href="/signout">Sign out</a> %>
                <%= current_user.email %> | <%= link_to "Sign out", '/signout' %>
            <% else %>
              <%= link_to "Sign up", 'signup' %> | <%= link_to "Sign in", '/signin' %>
            <% end %>
                </li>
            </ul>
        </div>
    </div>
  </nav>

     
      <div class="container">
     

      <span id="alert"><%= flash[:alert] %></span>
      <span id="notice"><%= flash[:notice] %></span>

     
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/admin_user.html.erb
<br>
<% if @users.any? %>
  <h4>Here are the users in the database</h4>

  <% @users.each do |user| %>
    <ul>
      <li>
        <%= link_to user.email, edit_user_path(user) %>
        
      </li>
    </ul>
  <% end %>
<% else %>
  <p>There are no users.</p>
<% end %>

app/views/users/edit.html.erb
<% if @user.images.any? %>
  <h4>Here are the images the user created</h4>

  <% @user.images.each do |image| %>
    <ul>
      <li>
        <%= link_to image.id, edit_user_image_path(@user, image) %>

        <%= image_tag "#{image.url}", height: 300 %>
        
      </li>
    </ul>
  <% end %>
<% else %>
  <p>There are no images.</p>
<% end %>

<p><%= link_to "Delete user", user_path(@user),
                                      :data => {:confirm => "Are you sure?",
                                        :method => "delete"} %></p>


<p><%= link_to "Return to users list", admin_path %></p>

app/views/users/new.html.erb
<h1> Sign up</h1>
<%= form_for @user do |f| %>
  <%= f.label "Email" %>
  <%= f.text_field :email %>
  <%= f.label "Password" %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit "Sign Up" %>
<% end %>

app/views/users/show.html.erb
<h1>Welcome to Sticker!</h1>

<p><%= link_to "Sign Up", 'signup' %></p>

<p><%= link_to "Sign In", 'signin' %></p>

<p><%= link_to "add image", new_user_image_path(@user)%></p> 